id: P010508
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ4690
  title: འབྲུག་པ་ཀུན་ལེགས་ཀྱི་རྣམ་ཐར་མོན་སྤ་གྲོ་སོགས་ཀྱི་མཛད་སྤྱོད་།
  author: ''
  volumes:
    efa267e88c4447a48095940912951af8:
      image_group_id: I1CZ4999
      title: ''
      volume_number: 1
      total_pages: 134
