id: I823B8922
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:31:26+00:00'
last_modified: '2022-06-08T14:06:47.041998+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ4690
  title: འབྲུག་པ་ཀུན་ལེགས་ཀྱི་རྣམ་ཐར་མོན་སྤ་གྲོ་སོགས་ཀྱི་མཛད་སྤྱོད་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3E8E:
      image_group_id: I1CZ4999
      title: ''
      total_pages: 134
      order: 1
      base_file: 3E8E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
